language: c
sudo: true
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.02.1
  - OCAML_VERSION=4.01.0
  - OCAML_VERSION=4.00.1
  - OCAML_VERSION=3.12.1
os:
- linux
